config/routes.rb
require "sidekiq/web"
require "mini_scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"
require_dependency "permalink_constraint"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[\w.\-]+?/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do
  relative_url_root = (defined?(Rails.configuration.relative_url_root) && Rails.configuration.relative_url_root) ? Rails.configuration.relative_url_root + '/' : '/'

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  post "webhooks/aws" => "webhooks#aws"
  post "webhooks/mailgun"  => "webhooks#mailgun"
  post "webhooks/mailjet"  => "webhooks#mailjet"
  post "webhooks/mandrill" => "webhooks#mandrill"
  post "webhooks/sendgrid" => "webhooks#sendgrid"
  post "webhooks/sparkpost" => "webhooks#sparkpost"

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    # only allow sidekiq in master site
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new(require_master: true)
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  resources :about do
    collection do
      get "live_post_counts"
    end
  end

  get "finish-installation" => "finish_installation#index"
  get "finish-installation/register" => "finish_installation#register"
  post "finish-installation/register" => "finish_installation#register"
  get "finish-installation/confirm-email" => "finish_installation#confirm_email"
  put "finish-installation/resend-email" => "finish_installation#resend_email"

  resources :directory_items

  get "site" => "site#site"
  namespace :site do
    get "settings"
    get "custom_html"
    get "banner"
    get "emoji"
  end

  get "site/basic-info" => 'site#basic_info'
  get "site/statistics" => 'site#statistics'
  get "site/selectable-avatars" => "site#selectable_avatars"

  get "srv/status" => "forums#status"

  get "wizard" => "wizard#index"
  get 'wizard/steps' => 'steps#index'
  get 'wizard/steps/:id' => "wizard#index"
  put 'wizard/steps/:id' => "steps#update"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    get 'plugins' => 'plugins#index'

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports" => "reports#index"
    get "reports/bulk" => "reports#bulk"
    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        get 'bulk'
        get 'bulk-complete' => 'groups#bulk'
        put 'bulk' => 'groups#bulk_perform'
      end
      member do
        put "owners" => "groups#add_owners"
        delete "owners" => "groups#remove_owner"
      end
    end

    get "groups/:type" => "groups#show", constraints: AdminConstraint.new
    get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

    get "moderation_history" => "moderation_history#index"

    resources :users, id: RouteFormat.username, except: [:show] do
      collection do
        get "list" => "users#index"
        get "list/:query" => "users#index"
        get "ip-info" => "users#ip_info"
        delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
        get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      delete "penalty_history", constraints: AdminConstraint.new
      put "suspend"
      put "delete_posts_batch"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "silence"
      put "unsilence"
      put "trust_level"
      put "trust_level_lock"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements" => "users#tl3_requirements"
      get "tl3_requirements"
      put "anonymize"
      post "reset_bounce_score"
      put "disable_second_factor"
    end
    get "users/:id.json" => 'users#show', defaults: { format: 'json' }
    get 'users/:id/:username' => 'users#show', constraints: { username: RouteFormat.username }
    get 'users/:id/:username/badges' => 'users#show'
    get 'users/:id/:username/tl3_requirements' => 'users#show'

    post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new
    post "users/invite_admin" => "users#invite_admin", constraints: AdminConstraint.new

    resources :impersonate, constraints: AdminConstraint.new

    resources :email, constraints: AdminConstraint.new do
      collection do
        post "test"
        get "sent"
        get "skipped"
        get "bounced"
        get "received"
        get "rejected"
        get "/incoming/:id/raw" => "email#raw_email"
        get "/incoming/:id" => "email#incoming"
        get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
        get "preview-digest" => "email#preview_digest"
        get "send-digest" => "email#send_digest"
        get "smtp_should_reject"
        post "handle_mail"
        get "advanced-test"
        post "advanced-test" => "email#advanced_test"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
        collection do
          post "roll_up"
        end
      end
      resources :screened_urls,         only: [:index]
      resources :watched_words, only: [:index, :create, :update, :destroy] do
        collection do
          get "action/:id" => "watched_words#index"
        end
      end
      post "watched_words/upload" => "watched_words#upload"
      resources :search_logs,           only: [:index]
      get 'search_logs/term/:term' => 'search_logs#term'
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/themes" => "themes#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
    get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
    put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index", as: 'flags_filtered'
    get "flags/topics/:topic_id" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"

    resources :flagged_topics, constraints: StaffConstraint.new
    resources :themes, constraints: AdminConstraint.new

    post "themes/import" => "themes#import"
    post "themes/upload_asset" => "themes#upload_asset"
    post "themes/generate_key_pair" => "themes#generate_key_pair"
    get "themes/:id/preview" => "themes#preview"

    scope "/customize", constraints: AdminConstraint.new do
      resources :user_fields, constraints: AdminConstraint.new
      resources :emojis, constraints: AdminConstraint.new

      get 'themes/:id/:target/:field_name/edit' => 'themes#index'
      get 'themes/:id' => 'themes#index'
      get "themes/:id/export" => "themes#export"

      # They have periods in their URLs often:
      get 'site_texts'             => 'site_texts#index'
      get 'site_texts/:id.json'    => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      get 'site_texts/:id'         => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id.json'    => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id'         => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id.json' => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id'      => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }

      get 'email_templates'          => 'email_templates#index'
      get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
      put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
      delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    get "dashboard" => "dashboard_next#index"
    get "dashboard/general" => "dashboard_next#general"
    get "dashboard/moderation" => "dashboard_next#moderation"
    get "dashboard/security" => "dashboard_next#security"
    get "dashboard/reports" => "dashboard_next#reports"

app/controllers/finish_installation_controller.rb
class FinishInstallationController < ApplicationController
  skip_before_action :check_xhr, :preload_json, :redirect_to_login_if_required
  layout 'finish_installation'

  before_action :ensure_no_admins, except: ['confirm_email', 'resend_email']

  def index
  end

  def register
    @allowed_emails = find_allowed_emails

    @user = User.new
    if request.post?
      email = params[:email].strip
      raise Discourse::InvalidParameters.new unless @allowed_emails.include?(email)

      if existing_user = User.find_by_email(email)
        @user = existing_user
        send_signup_email
        return redirect_confirm(email)
      end

      @user.email = email
      @user.username = params[:username]
      @user.password = params[:password]
      @user.password_required!

      if @user.save
        @user.change_trust_level!(1) if @user.trust_level < 1
        send_signup_email
        return redirect_confirm(@user.email)
      end

    end
  end

  def confirm_email
    @email = session[:registered_email]
  end

  def resend_email
    @email = session[:registered_email]
    @user = User.find_by_email(@email)
    send_signup_email if @user.present?
  end

  protected

  def send_signup_email
    email_token = @user.email_tokens.unconfirmed.active.first

    if email_token.present?
      Jobs.enqueue(:critical_user_email,
                   type: :signup,
                   user_id: @user.id,
                   email_token: email_token.token)
    end
  end

  def redirect_confirm(email)
    session[:registered_email] = email
    redirect_to(finish_installation_confirm_email_path)
  end

  def find_allowed_emails
    return [] unless GlobalSetting.respond_to?(:developer_emails) && GlobalSetting.developer_emails.present?
    GlobalSetting.developer_emails.split(",").map(&:strip)
  end

  def ensure_no_admins
    preload_anonymous_data
    raise Discourse::InvalidAccess.new unless SiteSetting.has_login_hint?
  end
end

app/views/finish_installation/confirm_email.html.erb
<h1><%= t 'finish_installation.confirm_email.title' %></h1>

<%= raw(t 'finish_installation.confirm_email.message', email: @email) %>

<div class='row'>
  <%= button_to(finish_installation_resend_email_path, method: :put, class: 'wizard-btn primary') do %>
    <%= t 'finish_installation.resend_email.title' %>
  <% end %>
</div>

app/views/finish_installation/index.html.erb
<h1><%= t 'finish_installation.congratulations' %></h1>

<div class='row'>
  <%= image_tag "/images/wizard/tada.svg", class: "tada" %>
</div>

<div class='row help-text'>
  <%= t 'finish_installation.register.help' %>
</div>

<div class='row'>
  <%= link_to(finish_installation_register_path, class: 'wizard-btn primary') do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="14px" height="14px" viewBox="0 0 448 512">
      <path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path>
    </svg>

    <%= t 'finish_installation.register.button' %>
  <% end %>
</div>

app/views/finish_installation/register.html.erb
<h1><%= t 'finish_installation.register.title' %></h1>

<%- if @allowed_emails.present? %>
  <%= form_tag(finish_installation_register_path) do %>

    <div class='wizard-field text-field'>
      <label for="email">
        <span class="label-value"><%= t 'js.user.email.title' %></span>
      </label>

      <div class='input-area'>
        <!--email_off-->
        <%= select_tag :email, options_for_select(@allowed_emails, selected: params[:email]), class: 'combobox' %>
        <!--/email_off-->
      </div>
    </div>

    <div class='wizard-field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="username">
        <span class="label-value"><%= t 'js.user.username.title' %></span>
      </label>

      <div class='field-description'><%= t 'js.user.username.instructions' %></div>

      <div class='input-area'>
        <%= text_field_tag(:username, params[:username]) %>
      </div>
      <%- @user.errors[:username].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <%- end %>
    </div>

    <div class='wizard-field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="password">
        <span class="label-value"><%= t 'js.user.password.title' %></span>
      </label>

      <div class='field-description'><%= t 'js.user.password.instructions', count: SiteSetting.min_admin_password_length  %></div>

      <div class='input-area'>
        <%= password_field_tag(:password, params[:password]) %>
      </div>
      <% @user.errors[:password].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <% end %>
    </div>

    <%= submit_tag(t('finish_installation.register.button'), class: 'wizard-btn primary') %>

  <%- end %>
<%- else -%>
  <p><%= raw(t 'finish_installation.register.no_emails') %></p>
<%- end %>

app/views/finish_installation/resend_email.html.erb
<h1><%= t 'finish_installation.resend_email.title' %></h1>

<%= raw(t 'finish_installation.resend_email.message', email: @email) %>